turi:proofread-1
boyeonihn/freecodecamp-korean pull request #6
Opened 2022-07-19 08:47 UTC by sookm

-문장과 단어 조금 수정했습니다.
-감수자 코멘트 삭제했습니다.
substr() 과 substring() 차이를 언급하지 않아도 괜찮은지 여쭙습니다.

2022-07-19 12:59 UTC, boyeonihn commented
@sookm 
안녕하세요! 수정 내역 확인했습니다, 감사해요. 

제가 원문에서는 substr()이었지만 substring()으로 수정한 이유가 영문 MDN 문서에서 substr() 사이트에 이렇게 표기되어서인데요: 
![Screenshot 2022-07-19 214424](https://user-images.githubusercontent.com/95451902/179753324-6a81a756-ad50-452d-b6d0-29d194faa8bc.png)

사용이 권장되지 않은 Deprecated 메서드인데, substr()과 substring()의 차이점을 굳이 설명하지 않아도 된다고 생각하는데, 어떻게 생각하시는지 궁금합니다 !

수정본에 제가 코멘트를 달았으니 피드백 부탁드려요!

2022-07-19 13:20 UTC, sookm commented
네 번역자님 판단이 맞는거 같습니다. :)

2022-07-19 22:34 UTC, boyeonihn requested changes
substr()  & substring() 메서드 추가내용 관련 코멘트도 한 번 리뷰해주세요 :D

2022-07-19 22:34 UTC, boyeonihn commented on javascript-reverse-string.md
>  - `substring()` 메서드는 기존 문자열의 특정 시작 인덱스부터 끝 인덱스 범위 내에 위치한 문자를 부분 문자열로 반환합니다.
이 라인 아래에 부연 설명을 하면 어떨지, 감수자님의 의견이 궁금해요! 


**2016년에 작성된 영어 원문에서는 String.prototype.substr() 메서드를 소개했으나, 현재 String.substr()에 대한 [MDN](https://developer.mozilla.org/ko/docs/Web/JavaScript/Reference/Global_Objects/String/substr) 문서에 따르면 substr() 메서드의 사용은 더 이상 권장되지 않기 때문에 번역문에는 String.prototype.substring() 메서드를 대신 설명합니다.** 


그리고 substr()과 substring()의 차이점을 포함해야 한다고 생각하신다면 아래처럼 설명하는 게 어떨지 알려주세요.



**substr()과 substring() 메서드는 부분 문자열을 반환하는 메서드이고, 두 개의 매개변수를 갖고 있습니다. 이 두 메서드의 첫 번째 매개변수는 동일하게 반환되는 문자열의 시작 인덱스입니다.  이 두 메서드의 차이점은 substr() 메서드의 두 번째 매개변수는 추출할 문자들의 총 숫자이지만, substring()의 두 번째 매개변수는 반환문자열의 마지막 인덱스라는 점입니다.**

2022-07-19 22:34 UTC, boyeonihn commented on javascript-reverse-string.md
>  - `substring()` 메서드는 기존 문자열의 특정 시작 인덱스부터 끝 인덱스 범위 내에 위치한 문자를 부분 문자열로 반환합니다.
@sookm 추가할 이 굵은체 부분도 한 번 읽어봐주시고 의견/제안 해주세요 :D 

substr()과 substring()의 차이점은 굳이 언급하지 않아도 된다고 동의했으니, 첫번째 bolded한 부분만 확인해주시면 될 것 같습니다. 감사해요!

2022-07-20 01:56 UTC, sookm commented on javascript-reverse-string.md
>  - `substring()` 메서드는 기존 문자열의 특정 시작 인덱스부터 끝 인덱스 범위 내에 위치한 문자를 부분 문자열로 반환합니다.
안녕하세요! @boyeonihn 
제가 감수자 코멘트인줄 착각하고 저 부분을 모두 삭제했습니다. 

**2016년에 작성된 영어 원문에서는 String.prototype.substr() 메서드를 소개했으나, 현재 String.substr()에 대한 [MDN](https://developer.mozilla.org/ko/docs/Web/JavaScript/Reference/Global_Objects/String/substr) 문서에 따르면 substr() 메서드의 사용은 더 이상 권장되지 않기 때문에 번역문에는 String.prototype.substring() 메서드를 대신 설명합니다.**

이 문장을 번역문에 포함하시는 거라면 설명이 충분한 것으로 보입니다 ! 
감사합니다 :D

2022-07-20 06:50 UTC, merged